name: Build Project (Release)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  address:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Build Preparation
      run: |
        chmod +x ./assets/IspInfo/getispinfo.sh
        ./assets/IspInfo/getispinfo.sh
    - name: Prepare Build Job
      uses: actions/upload-artifact@v4
      with:
        name: isp
        path: assets/IspInfo/*.xml

  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.runs-on }}
    needs: address

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - uses: actions/download-artifact@v4
      with:
        name: isp
        path: assets/IspInfo
    - name: Solution Compilation
      run: dotnet build --configuration Release
    - name: Testing
      run: dotnet test --no-build --configuration Release
        
