name: "Tracking the mail provider list"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '06 12 * * *'

jobs:
  track:
    name: Track
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false


    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'
        ref: ${{ github.ref }}
    - name: Download the list
      run: |
        bash -v public/Nettify/assets/IspInfo/getispinfo.sh
    - name: Add difference and push
      uses: EndBug/add-and-commit@v9
      with:
        message: upd - Updated ISP list (text)
        committer_name: Mail Provider Watch
        committer_email: actions@github.com
        add: 'public/Nettify/assets/IspInfo/isps.txt'
        push: true
